# Generated by Django 4.1.3 on 2023-05-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='facebook',
            field=models.CharField(max_length=50),
        ),
    ]
