# Generated by Django 4.1.3 on 2023-05-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='user-avatar.png', null=True, upload_to='users/'),
        ),
    ]
