# Generated by Django 4.1.3 on 2023-06-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_token_customer_token_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
