# Generated by Django 4.1.3 on 2023-05-23 16:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('img', models.ImageField(default='store/img/img_coming_soon.png', upload_to='store/img')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('sub', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0.0)),
                ('price_origin', models.FloatField(null=True)),
                ('image_course', models.ImageField(default='store/img/img_coming_soon.png', upload_to='store/img')),
                ('is_free', models.BooleanField(default=True)),
                ('describe', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('public_day', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.IntegerField(default=0)),
                ('vote', models.FloatField(blank=True, default=5, null=True)),
                ('star', models.TextField(default='<small class="fa fa-star text-primary mr-1"></small><small class="fa fa-star text-primary mr-1"></small><small class="fa fa-star text-primary mr-1"></small><small class="fa fa-star text-primary mr-1"></small><small class="fa fa-star text-primary mr-1"></small>')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.category')),
            ],
            options={
                'ordering': ('-public_day',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(default='', max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('img', models.ImageField(blank=True, default='store/img/img_coming_soon.png', null=True, upload_to='store/img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.course')),
            ],
        ),
    ]
