# Generated by Django 4.1.3 on 2023-05-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_category_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
