# Generated by Django 4.1.3 on 2023-05-24 11:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_category_courses_course_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='describe',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
