# Generated by Django 4.1.3 on 2023-05-25 14:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_course_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('video', models.CharField(max_length=500, null=True)),
                ('image_blog', models.ImageField(default='store/img/img_coming_soon.png', upload_to='store/img')),
                ('describe', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('public_day', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-public_day',),
            },
        ),
    ]
