# Generated by Django 4.1.3 on 2023-05-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
