# Generated by Django 4.1.3 on 2023-05-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
