# Generated by Django 4.1.3 on 2023-05-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_comment_user_first_name_comment_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_avatar',
            field=models.ImageField(default='user-avatar.png', upload_to='media/users'),
        ),
    ]
