# Generated by Django 4.1.3 on 2023-05-27 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0013_alter_comment_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_avatar',
            field=models.ImageField(default='user-avatar.png', upload_to='users/'),
        ),
        migrations.CreateModel(
            name='Blogcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_avatar', models.ImageField(default='user-avatar.png', upload_to='users/')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
