# Generated by Django 4.1.3 on 2023-05-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_alter_comment_user_avatar_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
