# Generated by Django 4.1.3 on 2023-06-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_blogcomment_image_comment_image_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='comments/'),
        ),
    ]
