# Generated by Django 4.1.3 on 2023-06-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_alter_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='viewed',
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(default='10 phút', max_length=100),
        ),
    ]
