# Generated by Django 4.1.3 on 2023-06-02 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0018_remove_course_viewed_course_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('name_course', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.course')),
            ],
        ),
    ]
