# Generated by Django 4.1.3 on 2023-06-11 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_alter_course_price_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paidcourses',
            name='name_course',
        ),
    ]
