# Generated by Django 4.1.3 on 2023-06-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0022_remove_paidcourses_name_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục bánh'},
        ),
    ]
