# Generated by Django 4.1.3 on 2023-06-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0023_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Danh mục bánh'},
        ),
    ]
