# Generated by Django 4.1.3 on 2023-06-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0025_alter_blog_options_alter_blogcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-public_day',), 'verbose_name_plural': 'Khóa học bánh'},
        ),
        migrations.AlterModelOptions(
            name='paidcourses',
            options={'verbose_name_plural': 'Danh sách user đã thanh toán'},
        ),
    ]
