# Generated by Django 4.1.3 on 2023-06-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0026_alter_course_options_alter_paidcourses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidcourses',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paidcourses',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paidcourses',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paidcourses',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
